name: dependabot-auto-merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const pull_number = context.payload.pull_request.number
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number,
              merge_method: 'squash'
            })
